version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bun:latest
    container_name: bunjs
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - GOOGLE_ID=720803559255-ae64jet8mihdeo8nati1sp1hm7e00l7c.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - REDIRECT_URL=https://mind.eng.cmu.ac.th/redirect #redirect form frontend http://localhost:3000
      - PGSQL_HOST=ep-empty-dust-a1wnsfia-pooler.ap-southeast-1.aws.neon.tech
      - PGSQL_PORT=5432
      - PGSQL_DATABASE=verceldb
      - PGSQL_USER=default  
      - PGSQL_PASSWORD=oh80MiHuWFpt 
    restart: always


